FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm i

# Expose port
EXPOSE 3000 24678

ENTRYPOINT ["dumb-init", "--"]

# Start development server
CMD ["pnpm", "dev", "--", "--host", "0.0.0.0", "--port"]